main.tf

Add security group for load balancer.

Update Security Groups

---

.github/workflows/pr.yml
README.md

This PR is to add a default readme file

Add default readme

---

main.tf

Add MySQL db

---

.github/workflows/pr.yml
README.md
docker/scripts/init.sh
terraform/.checkov.yml

Implement checkov and shellcheck

---

docker/scripts/init.sh
terraform/ecs.tf

Fix root issue

---

.github/workflows/cicd.yml
.github/workflows/cleanup.yml
.github/workflows/pr.yml
docker/scripts/init.sh
terraform/ecs.tf
terraform/variables.tf

This will force a refresh (empty db) of the database.

Add logic for force refresh

---

terraform/ecs.tf
terraform/iam.tf
terraform/modules/ecs_service/main.tf
terraform/modules/ecs_service/variables.tf
terraform/task-definitions/mft.tftpl

Replace the "ecsTaskExecutionRole" created in the UI by a role created with terraform.

Create role for ECS

---

.github/workflows/cicd.yml
.github/workflows/cleanup.yml
.github/workflows/pr.yml
README.md
terraform/lb.tf
terraform/variables.tf
terraform/vpc.tf

Replace environment variable (VPC) with data source.
Add missing environment variables in the readme.

Replace environment variable with data source

---

README.md
terraform/db.tf
terraform/ecs.tf
terraform/modules/ecs_service/main.tf
terraform/modules/ecs_service/variables.tf
terraform/variables.tf

Add 3 variables, DB_INSTANCE_CLASS, TASK_DEFINITION_CPU and TASK_DEFINITION_MEMORY

Add environment variables for parameters

---

docker/scripts/init.sh

Remove n option

---

docker/scripts/init.sh

Add force option to cp

---

terraform/ecs.tf
terraform/iam.tf
terraform/modules/ecs_service/main.tf
terraform/modules/ecs_service/variables.tf

Enable ssh in containers

---

docker/scripts/init.sh
terraform/.checkov.yml
terraform/iam.tf

Update hostname name

---

.github/workflows/cicd.yml
.github/workflows/cleanup.yml
.github/workflows/pr.yml
docker/scripts/init.sh
terraform/lb.tf
terraform/modules/ecs_service/main.tf

PR to cleanup code and remove condition for cleanup pipeline.

Update default ports

---

docker/Dockerfile
docker/configs/fluent-bit.conf
docker/scripts/fluent-bit.conf
docker/scripts/fluent-bit.repo
docker/scripts/init.sh
terraform/iam.tf

Installing fluent-bit

---

.github/workflows/cicd.yml

refactor cicd

---

.github/workflows/cicd.yml
.github/workflows/pr.yml

add missing output to cicd

---

docker/Dockerfile

upgrade to v 7.7.1

---

docker/configs/fluent-bit.conf

add upgrade logs to fluent-bit

---

docker/Dockerfile

Upgrade GA to 7.8.0

---

README.md
terraform/workload/cloudwatch.tf
terraform/workload/cw.tf
terraform/workload/sns.tf
terraform/workload/variables.tf

Add alarms for DB

---

terraform/workload/cloudwatch.tf

add ecs alarms

---

terraform/workload/cloudwatch.tf

add health check LB alarm
